### ISSUE TITLE
Compatibility with .NET 6

### ISSUE THREAD

**Issue by vhugogarcia** [KenticoDevTrev/MVCCaching#7]
Hello Trevor, 

First, I would like to thank you for this amazing package, it really helps a lot to reduce the time of development to implement CACHE for Xperience CMS projects on .NET.

However, I'm trying to implement CI on my project and since I'm on .NET 6, I see an error when it compiles on the CI server: 
`error NU1202: Package MVCCaching.Kentico.Core 13.0.2 is not compatible with net60 (.NETFramework,Version=v6.0). Package MVCCaching.Kentico.Core 13.0.2 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)`

Do you think you can help us to increase the support version of the MVCCaching nuget package? please

Thanks in advance,
Victor

**Comment by KenticoDevTrev** [comment]
I'm very confused, there is no issue with MVCCaching and .net 6, it's working fine on our .Net 6 instance, even on the nuget package it shows net6.0 compatability:

[https://www.nuget.org/packages/MVCCaching.Kentico.Core/](https://www.nuget.org/packages/MVCCaching.Kentico.Core/)

I Think you need to update the NuGetToolInstaller in your pipeline, 
https://stackoverflow.com/questions/64848744/cant-build-net-5-in-pipeline

Try that?  What's your build pipeline?

**Comment by vhugogarcia** [comment]
Hello @KenticoDevTrev ,

Thank you for the faster response.

Find below the pipeline:

```
image: microsoft/dotnet:sdk

pipelines:
  branches:
    develop:
      - step:
          name: Build
          caches:
            - dotnetcore
          script:
            - dotnet restore src/solution_name.sln
            - dotnet build src/solution_name.sln --no-restore --configuration Release
```

Let me see if I can get the nugettoolInstaller task work. I'm using Bitbucket pipelines, so it should be supported.

**Comment by KenticoDevTrev** [comment]
Here's our pipeline if it helps at all :) 

```yaml
# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'MVC/*' # same as '/' for the repository root
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/MVC.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-Location
      Get-ChildItem -Path ./ -Filter *.template -Recurse -File -Name | ForEach-Object {
          $newName = $_.Replace(".template", ".config")
          $fileName = Split-Path $newName -leaf
          Write-Host $fileName ">" $newName
          Rename-Item $_ -NewName $fileName
      }

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
```
